# API Configuration
api:
  alpha_vantage:
    key: ${ALPHA_VANTAGE_API_KEY}
    base_url: "https://www.alphavantage.co/query"
    
  newsapi:
    key: ${NEWSAPI_KEY}
    base_url: "https://newsapi.org/v2"
    
  nasdaq_data_link:
    key: ${NASDAQ_DATA_LINK_KEY}
    base_url: "https://data.nasdaq.com/api/v3"
    
  yahoo_finance:
    enabled: true
    
  iex_cloud:
    enabled: false
  fred:
    enabled: false

# Database Configuration
database:
  type: "sqlite"
  path: "${DATABASE_PATH:-data/market_data.db}"

# Model Configuration
models:
  lstm:
    sequence_length: 60
    hidden_units: 50
    layers: 2
    dropout: 0.2
    learning_rate: 0.001
    
  cnn:
    filters: [32, 64, 128]
    kernel_sizes: [3, 3, 3]
    pool_size: 2
    dropout: 0.25
    learning_rate: 0.001
    
  attention:
    d_model: 128
    num_heads: 8
    num_layers: 4
    dropout: 0.1
    learning_rate: 0.0001

# Training Configuration
training:
  batch_size: 32
  epochs: 100
  validation_split: 0.2
  early_stopping_patience: 10
  save_best_only: true

# Data Configuration
data:
  symbols: ["AAPL", "GOOGL", "MSFT", "AMZN", "TSLA", "NVDA", "META"]
  timeframe: "1min"
  features: [
    "open", "high", "low", "close", "volume",
    "sma_20", "ema_20", "rsi", "macd", "bollinger_bands"
  ]
  target: "close"
  lookback_window: 60

# Prediction Configuration
prediction:
  confidence_threshold: 0.7
  prediction_horizon: 10
  update_frequency: 60

# News sentiment configuration
news:
  sources: ["reuters", "bloomberg", "cnbc", "marketwatch"]
  languages: ["en"]
  sentiment_threshold: 0.1

# Logging Configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  file: "logs/market_predictor.log"
  max_size: "10MB"
  backup_count: 5
