# Massive 3B Parameter Model Configuration
model:
  num_experts: 128
  expert_hidden_size: 4096
  num_layers: 48
  num_heads: 32
  d_model: 8192
  dropout_rate: 0.1
  max_seq_length: 2048

training:
  epochs: 100
  batch_size: 8
  learning_rate: 1e-4
  mixed_precision: true
  gradient_clip_norm: 1.0
  weight_decay: 0.01
  warmup_steps: 10000
  max_steps: 500000

data:
  collection_years: 10
  max_symbols_per_source: 5000
  parallel_requests: 50
  sequence_length: 2048
  test_size: 0.1
  val_size: 0.1
  data_types: ['stocks', 'crypto', 'forex', 'commodities', 'indices', 'bonds', 'options']
  timeframes: ['1m', '5m', '15m', '1h', '1d', '1wk']
  features_per_symbol: 200
  target_horizons: [1, 5, 15, 60, 240, 1440]

distributed:
  num_gpus: -1
  mixed_precision: true
  xla_jit: true

logging:
  log_dir: 'logs/massive_training'
  checkpoint_dir: 'checkpoints/massive_model'
  save_steps: 1000
  eval_steps: 500

api:
  alpha_vantage:
    key: ${ALPHA_VANTAGE_API_KEY}
  polygon:
    key: ${POLYGON_API_KEY}
  twelve_data:
    key: ${TWELVE_DATA_API_KEY}
  newsapi:
    key: ${NEWSAPI_KEY}
  twitter_bearer:
    key: ${TWITTER_BEARER_TOKEN}
  fred:
    key: ${FRED_API_KEY}